steps:
  # Build API image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/stress-api:${SHORT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/stress-api:latest'
      - '-f'
      - 'infrastructure/Dockerfile'
      - '.'

  # Build Streamlit image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/stress-streamlit:${SHORT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/stress-streamlit:latest'
      - '-f'
      - 'infrastructure/Dockerfile.streamlit'
      - '.'

  # Push API image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/stress-api:${SHORT_SHA}'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/stress-api:latest'

  # Push Streamlit image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/stress-streamlit:${SHORT_SHA}'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/stress-streamlit:latest'

  # Deploy API to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'stress-api'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/stress-api:${SHORT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-secrets'
      - 'API_KEY=stress-api-key:latest'
      - '--set-env-vars'
      - 'MODEL_PATH=models/stress_model.joblib,LOG_LEVEL=INFO,LOG_FORMAT=json'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--concurrency'
      - '80'

  # Get API URL and deploy Streamlit
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        API_URL=$(gcloud run services describe stress-api --region ${_REGION} --format 'value(status.url)')
        gcloud run deploy stress-streamlit \
          --image ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/stress-streamlit:${SHORT_SHA} \
          --region ${_REGION} \
          --platform managed \
          --allow-unauthenticated \
          --set-secrets API_KEY=stress-api-key:latest \
          --set-env-vars STREAMLIT_API_URL=$${API_URL} \
          --memory 512Mi \
          --cpu 1 \
          --min-instances 0 \
          --max-instances 5

substitutions:
  _REGION: us-central1
  _REPOSITORY: stress-prediction

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/stress-api:${SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/stress-api:latest'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/stress-streamlit:${SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/stress-streamlit:latest'
